disabled_rules:
  - trailing_whitespace
  - colon
  - comma
  - explicit_init
  - force_try
  - file_header
  - no_fallthrough_only
  - pattern_matching_keywords
excluded:
  - Pods
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - explicit_init
  - extension_access_modifier
  - fatal_error_message
  - file_header
  - file_name
  - first_where
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - nimble_operator
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - single_test_class
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

identifier_name:
  excluded:
    - id
line_length: 2850000
function_body_length: 50
function_parameter_count: 5
file_length:
  warning: 500
  error: 1200
number_separator:
  minimum_length: 5
